list index out of range
File "/home/gitlab-runner/builds/7a4715f2/0/docs/itdocs/venv/lib/python3.6/site-packages/mkdocs_new_features_notifier/plugin.py", line 74, in on_files
    if file.src_path.split('.')[1] in ['markdown', 'mdown', 'mkdn', 'mkd', 'md']:
IndexError: list index out of range

And another update for documentation:
This plugi not work with awesome-pages plugin for MkDocs. 
To make it work, need to create folder "Updates" in docs root folder. Create file new-features.md in it.
From plugin.py delete or mask function on_nav().

Q: How to make it work with Git[Hub/Lab] Runner? The file versions.txt is owerwrited ewery time.... So, no new versions...